server:
  port: 8082

spring:
  application:
    name: board

  datasource:
    url: jdbc:postgresql://board_db:${BOARD_DB_PORT}/${BOARD_DB_NAME}
    username: ${BOARD_DB_USER}
    password: ${BOARD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
